# Define UI for application for Data Visualization
ui <- dashboardPage(skin = "black",
                    dashboardHeader(title =  tags$a(href='https://www.statmodeller.com/',  #Adding Company name
                                                    tags$img(src='https://statmodeller.com/wp-content/uploads/2019/12/cropped-Stat-Modeller-Logo-Copy-3.png',
                                                             height = '45', width = '50'), 'Stat Modeller'),titleWidth =250,
                                    tags$li(class = "dropdown", tags$a(href = 'https://drive.google.com/file/d/100SR9uRjT3HTsMPcg_A6OEvJxV_g_JD_/view?usp=sharing','Web Application for Statistical Analysis', height = "20px")),
                                    tags$li(class = "dropdown", tags$a(HTML(paste(uiOutput("Refresh1")))))), 
                    #option for file uploading
                    dashboardSidebar(width = 250,
                                     radioButtons("fileType_Input",
                                                  label = h4("Choose file type"),
                                                  choices = list(".csv/txt" = 1, ".xlsx" = 2),
                                                  selected = 1,
                                                  inline = TRUE
                                     ),
                                     fileInput(
                                       'file1',
                                       h4('Upload Your Data'),
                                       accept = c(
                                         'text/csv',
                                         'text/comma-separated-values,text/plain',
                                         '.csv',
                                         '.xlsx'
                                       )),
                                     # create a button on sidebar menu             
                                     sidebarMenu(
                                       menuItem("Raw Data", tabName = "RawData",
                                                icon = icon("table")),
                                       menuItem("Data Summary", tabName = "DataSummary",
                                                icon = icon("calculator")),
                                       menuItem("Histogram", tabName ="Histogram",
                                                icon = icon("chart-bar")),
                                       menuItem("Charts", tabName = "Charts",
                                                icon = icon("bar-chart-o")),
                                       menuItem("Correlation", tabName = "Correlation",
                                                icon = icon("chart-bar")),
                                       menuItem("Regression", tabName = "Regression",
                                                icon = icon("chart-line"))
                                     ),
                                     downloadButton("report", "Download",style = "color: white; background-color:#4682b4")),
                    dashboardBody(tags$head(tags$style("section.content { overflow-y: hidden; }")),
                                  tabItems(tabItem( tabName = "RawData",fluidRow(
                                    box(title = "View Data", width = NULL,
                                        status = "primary", solidHeader = TRUE,
                                        collapsible = TRUE,
                                        DT::dataTableOutput('contents'), background = "gray"))),
                                    tabItem(tabName = "DataSummary",
                                            box(title = "Choice of Variables", status = "primary",
                                                solidHeader = TRUE,collapsible = TRUE, 
                                                uiOutput('sumcheckbox'), width = 3),
                                            box(title ="DataSummary", status = "primary",
                                                solidHeader =TRUE,collapsible =TRUE,
                                                verbatimTextOutput("summary"),height =450 , width = 10),
                                    ),
                                    tabItem(tabName = "Histogram",
                                            box(title = "Histogram", status = "primary", 
                                                solidHeader = TRUE,collapsible = TRUE,
                                                plotlyOutput('Plothist', height =400)),
                                            box(title = "Choose variables for Histogram", status = "primary", 
                                                uiOutput('select')),
                                    ),
                                    tabItem(tabName = "Charts",
                                            box(title = "Choose variables for Charts", status = "primary", 
                                                solidHeader = TRUE,collapsible = TRUE,
                                                selectInput(inputId = "y", label = "Select y-axis Variable:",
                                                            choices = NULL),
                                                selectInput(inputId = "x", label = "Select x-axis Variable:",
                                                            choices = NULL)),
                                            box(title = "Barplot", status ="primary", solidHeader = TRUE,
                                                collapsible = TRUE,plotOutput('plot', height = 300)),
                                            box(title = "Plot types", status = "primary", 
                                                solidHeader = TRUE,collapsible = TRUE,
                                                selectInput(
                                                  inputId = "plot_type",
                                                  label = "Select the plot type",
                                                  choices = c("scatter plot", "boxplot"))
                                            ),
                                            box(title = , status = "primary", 
                                                solidHeader = TRUE,collapsible = TRUE, 
                                                plotOutput('plot1', height = 300)),
                                    ),
                                    tabItem(tabName = "Correlation",
                                            box(title = "Choose of Variables", status = "primary",
                                                solidHeader = TRUE,collapsible = TRUE, 
                                                uiOutput('checkbox'), width = 3),
                                            box(title = "Correlation of the Data", status = "primary",
                                                solidHeader = TRUE,collapsible = TRUE,
                                                verbatimTextOutput('Correlation'),height =300 , width = 12),
                                            box(title = "Visualization of correlation matrix", status ="primary", solidHeader = TRUE,
                                                collapsible = TRUE,
                                                plotOutput('Correlationplot'),height =450 , width = 12),
                                    ),
                                    tabItem(tabName = "Regression",
                                            box(title = "Dependent Variable", status = "primary",
                                                solidHeader = TRUE,collapsible = TRUE, 
                                                uiOutput('yvariables'), width = 4),
                                            box(title = "Independent Variables",status = "primary",
                                                solidHeader = TRUE,collapsible = TRUE, 
                                                uiOutput('xvariables'), width = 4),
                                            box(title = "Multiple Liner Regression Summary", status ="primary", 
                                                solidHeader = TRUE,collapsible = TRUE,
                                                verbatimTextOutput('lmSummary'),height =300 , width = 12),
                                            box(title = "Visualization of Simple Liner Regression", 
                                                status ="primary", solidHeader = TRUE,
                                                collapsible = TRUE,
                                                plotOutput('diagnosticPlot'),height =700 , width = 12)
                                            
                                    )
                                    
                                  )
                    ))